server.name: kibana
server.host: '0.0.0.0'
#elasticsearch.hosts: [ "http://elasticsearch:9200" ]
elasticsearch.hosts: ['http://192.168.1.14:9200']
xpack.monitoring.ui.container.elasticsearch.enabled: true
#设置kibana中文显示
i18n.locale: zh-CN
