version: "3.5"

services:
  mysql:
    image: mysql:8.2.0
    container_name: mysql
    restart: "no"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/log:/var/log/mysql
      - ./mysql/initdb:/docker-entrypoint-initdb.d

  redis:
    image: redis:7.2.3
    container_name: redis
    restart: "no"
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data
      - ./redis/redis.conf:/etc/redis/redis.conf


  nacos:
    image: nacos/nacos-server:v2.3.0
    container_name: nacos
    restart: "no"
    privileged: true
    depends_on:
      - mysql
    ports:
      - 8848:8848
      - 8849:8849
      - 9848:9848
      - 9849:9849
    environment:
      - JVM_XMS=256m
      - JVM_XMX=256m
      - MODE=standalone
      - PREFER_HOST_MODE=hostname
    volumes:
      - ./nacos/logs:/home/nacos/logs
      - ./nacos/init.d/custom.properties:/home/nacos/init.d/custom.properties

  elasticsearch:
    image: elasticsearch:8.11.1
    container_name: elasticsearch
    restart: "no"
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - ./elasticsearch/img/elasticsearch.yml:/usr/share/elasticsearch/img/elasticsearch.yml
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/plugins:/usr/share/elasticsearch/plugins

  kibana:
    image: kibana:8.11.1
    container_name: kibana
    restart: "no"
    ports:
      - 5601:5601
    links:
      - mall4cloud-elasticsearch:elasticsearch
    environment:
      - SERVER_HOST=0.0.0.0
      - ELASTICSEARCH_HOSTS=http://192.168.1.14:9200
      - I18N_LOCALE=zh-CN
#或者通过配置文件   volumes:
#      - ./kibana/img/kibana.yml:/usr/share/kibana/img/kibana.yml
    depends_on:
      - elasticsearch

#  canal:
#    image: canal/canal-server:v1.1.6
#    container_name: canal
#    restart: "no"
#    ports:
#      - 11111:11111
#    volumes:
#      - ./canal/conf/example:/home/admin/canal-server/conf/example
#      - ./canal/conf/canal.properties:/home/admin/canal-server/conf/canal.properties
#      - ./canal/logs:/home/admin/canal-server/logs

  postgres:
    image: postgres:16.1
    container_name: postgresql
    restart: "no"
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/initdb:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456

  mongo:
    image: mongo:7.0.4
    container_name: mongo
    restart: "no"
    ports:
      - 27017:27017

  rabbitmq:
    image: rabbitmq:3.12.10-management
    container_name: rabbitmq
    restart: "no"
    privileged: true
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq/plugins/rabbitmq_delayed_message_exchange-3.12.0.ez:/plugins/rabbitmq_delayed_message_exchange-3.12.0.ez
    environment:
      - RABBITMQ_DELAYED_MESSAGE_ENABLED=true
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=123456
      - RABBITMQ_PLUGINS=enable --offline rabbitmq_delayed_message_exchange

#  excalidraw:
#    image: excalidraw/excalidraw:latest
#    container_name: excalidraw
#    restart: "no"
#    ports:
#      - 5000:80